name: talking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18+3
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.6
  get_it: ^7.6.6
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  logger: ^2.0.2+1
  provider: ^6.1.1
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.2.4
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/terms_conditions/
