name: talking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.5.0
  equatable: ^2.0.5
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_markdown: ^0.7.3
  formz: ^0.7.0
  freezed: ^2.5.2
  get_it: ^7.7.0
  go_router: ^14.0.2
  google_fonts: 6.2.1
  image_cropper: ^8.0.1
  injectable: ^2.4.4
  logger: ^2.4.0
  shared_preferences: ^2.3.1
  socket_io_client: ^2.0.3
  url_launcher: ^6.3.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/terms_conditions/
